### ISSUE TITLE
Creation of database trigger with match expression fails

### ISSUE THREAD

**Issue by StefanWachter1507** [mongodb/mongodbatlas-cloudformation-resources#592]
Note: I also filed this issue under [awscdk-resources-mongodbatlas/issues/80](https://github.com/mongodb/awscdk-resources-mongodbatlas/issues/80) because I do not know if this is a CDK related problem or related to the underlying CloudFormation resources.

I try to deploy a database trigger with a match expression (using the `CfnTrigger` CDK construct). The relevant section of the template is:

```
{
 "Description": "A test trigger",
 "Resources": {
  "triggerCD2FF5BD": {
   "Type": "MongoDB::Atlas::Trigger",
   "Properties": {
    "DatabaseTrigger": {
     "ServiceId": {
      "Ref": "SsmParameterValuepaymentdevelopmongoatlasserviceIdC96584B6F00A464EAD1953AFF4B05118Parameter"
     },
     "Database": "test",
     "Collection": "test",
     "OperationTypes": [
      "UPDATE"
     ],
     "Match": {
      "$expr": {
       "$and": [
        {
         "$eq": [
          "$fullDocument.availability.value",
          "AVAILABLE"
         ]
        },
        {
         "$ne": [
          "$fullDocument.retailPrice",
          "$fullDocumentBeforeChange.retailPrice"
         ]
        }
       ]
      }
     },
     "FullDocument": true,
     "FullDocumentBeforeChange": true,
     "SkipCatchupEvents": true,
     "TolerateResumeErrors": true,
     "Unordered": true
    },
    "Name": "MyTriggerName",
    "Type": "DATABASE",
    "EventProcessors": {
     "AWSEVENTBRIDGE": {
      "AWSConfig": {
       "AccountId": "733056268253",
       "Region": "eu-central-1",
       "ExtendedJsonEnabled": true
      }
     }
    },
    "AppId": {
     "Ref": "SsmParameterValuepaymentdevelopmongoatlasappIdC96584B6F00A464EAD1953AFF4B05118Parameter"
    },
    "ProjectId": {
     "Ref": "SsmParameterValuepaymentmongoatlasprojectIdC96584B6F00A464EAD1953AFF4B05118Parameter"
    }
   }
  }
 },
```

The dedployment results in the failure

```
9:14:31 AM | CREATE_FAILED        | MongoDB::Atlas::Trigger | triggerCD2FF5BD
Resource handler returned message: "Unable to complete request: Marshaling: Unable to convert type
caused by: Unsupported type interface {}" (RequestToken: 993412b5-8ea7-4a60-c3f6-e7983d7e9c57, HandlerErrorCode: GeneralServiceException)
```

When the `match` property is removed then the trigger is deployed successfully.

**Comment by Adelmar92** [comment]
hello @StefanWachter1507 the Match condition should be specified as an strigify version of a json expression, due to the fact that Cloud formation does not accept json structures as values of properties. you can get more information in the field description of the cloud formation resource: [link](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/registry/public-extensions/details/schema?arn=arn%3Aaws%3Acloudformation%3Aus-east-1%3A%3Atype%2Fresource%2Fbb989456c78c398a858fef18f2ca1bfc1fbba082%2FMongoDB-Atlas-Trigger)
<img width="1388" alt="image" src="https://github.com/mongodb/mongodbatlas-cloudformation-resources/assets/69170650/971bbd18-4385-47c1-a154-19d6a78ee204">

you can find an example on the repository: [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/trigger/trigger.json)

**Comment by Zuhairahmed** [comment]
thanks again @StefanWachter1507 , see related issue here if helpful: https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/88. resolving this issue and feel free to open a new issue if you need anything else. thank you
