### ISSUE TITLE
Cluster attribute not working: SrvAddress

### ISSUE THREAD

**Issue by mcintyre94** [mongodb/mongodbatlas-cloudformation-resources#62]
I've modified the `cluster.json` example to add an output for `SrvAddress`:

```
    "Outputs": {
        "Id": {
            "Description": "The ID of the cluster",
            "Value": {
                "Ref": "Cluster"
            }
        },
        "SrvAddress": {
            "Description": "Connection string for the cluster",
            "Value": {
                "Fn::GetAtt" : [ "Cluster", "SrvAddress" ]
            }
        }
    }
```

This is a documented attribute for the cluster in the README: https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cluster/README.md#attributes

When I deploy this to AWS I get an error message: Unable to retrieve SrvAddress attribute for MongoDB::Atlas::Cluster. Rollback requested by user. - and the stack is rolled back.

Is this the correct way to reference attributes for these Mongo Atlas custom resources?

I've also tried `"Fn::GetAtt" : [ "Cluster", "Properties.SrvAddress" ]` and `"Fn::GetAtt" : [ "Cluster", "/properties/SrvAddress" ]`

It does seem that I'm using the correct attribute - if I use a different attribute I get a different error "Requested attribute srvAddress does not exist in schema for MongoDB::Atlas::Cluster"

**Comment by jasonmimick** [comment]
Fixed with: https://github.com/jasonmimick/mongodbatlas-cloudformation-resources/pull/1
Coming soon

**Comment by 422158** [comment]
Have you ever got around on how to fix this? The problem seems to be with the read handler. My read handler dos not receive the API credentials as according to handler contract: _"The input to a read handler MUST contain either the primaryIdentifier or an additionalIdentifier. Any other properties MAY NOT be included in the request."_
That being said when the read handler invokes (and does not receive the api keys) it fails

**Comment by jasonmimick** [comment]
Hi-

Please find a [reference implementation](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/788972fffff4daca8c6122321bf8acd4c8d9434d/quickstart-mongodb-atlas/templates/mongodb-atlas.template.yaml#L237) for getting the SvrAddress in your Stack output.

There are issues with the current master branch resources, just as you pointed out. CFN had some platform changes which required additional work in the resources. For example, you will notice now that an AWS Secret is created and used during a READ, precisely because of the issue you pointed out. This all happens automatically, so no end user action needed, however it is relevant to your point.

This is fixed in the [qs-launch-update](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/qs-launch-update) branch.
Other options include:

- The [get-started-aws-cfn](https://github.com/mongodb-developer/get-started-aws-cfn) project
- [AWS MongoDB Atlas Quick Start](https://aws.amazon.com/quickstart/architecture/mongodb-atlas/)

Please test out with our new releases and reopen if you hit anything.
Thanks for your feedback.
