### ISSUE TITLE
Stack Run Failed after running Quick start

### ISSUE THREAD

**Issue by rajeshvinayagam-lab** [mongodb/mongodbatlas-cloudformation-resources#73]
@jasonmimick 

Quick Start Ran Successfully and was able to see them in the cloud-formation stack. But was getting an error when running the stack. Not sure what is the parameter that is missing.

![image](https://user-images.githubusercontent.com/76505827/106217155-a2459f00-61a2-11eb-92df-f5fba55b7f7f.png)

![image](https://user-images.githubusercontent.com/76505827/106217278-ec2e8500-61a2-11eb-925a-4cd2ec88fc88.png)

**Comment by mertsaygi** [comment]
My stack also failed with same problem. I resolved it via removing "Properties" from cfn-resources/project/mongodb-atlas-project.json. I added Name instead of that.

**Comment by jasonmimick** [comment]
This is fixed in the [qs-launch-update](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/qs-launch-update) branch.
Other options include:

- The [get-started-aws-cfn](https://github.com/mongodb-developer/get-started-aws-cfn) project
- [AWS MongoDB Atlas Quick Start](https://aws.amazon.com/quickstart/architecture/mongodb-atlas/)
