### ISSUE TITLE
Multiple mappings for same field not possible

### ISSUE THREAD

**Issue by matsekroth** [mongodb/mongodbatlas-cloudformation-resources#755]
### CloudFormation Template 
```
    const assetSearchIndex = new CfnSearchIndex(this, "AssetSearchIndex", {
      projectId: atlasProject.getAtt("Id").toString(),
      clusterName: props.clusterName,
      database: props.databaseName,
      collectionName: "collectionName",
      name: "searchFilterIndex",
      mappings: {
        fields: [
          "ownershipDetails.assetName:string",
          "ownershipDetails.assetName:autocomplete",
        ],
      },
    });
```

### Steps to Reproduce
Add the same fields but with different mappings, in my case I wanted a field to be mapped both for string filter and search and for autocomplete. 

### Expected Behavior
The field should be mapped twice as it does when done through the visual designer in Atlas. 
![image](https://github.com/mongodb/mongodbatlas-cloudformation-resources/assets/124593404/4b7d00aa-23ef-4497-92bc-d50982c5467f)

### Actual Behavior
The last entry for each field is the mapping that is recorded in the index. In this case it will be indexed only for autocomplete.

### Additional Context
Please contact me through email if more information about the CDK setup, templates or examples are needed.

**Comment by Adelmar92** [comment]
hello @matsekroth here is the proposal im working to fix this, now the client recieves a map[string]interface so you wont be to create something like this

"ownershipDetails.assetName:string",
 "ownershipDetails.assetName:autocomplete",

also there is a problem with the current way the Field mapping is defined, some data types requires complex properties, like the autocomplete for example, now how field is defined, you can only use the type
![image](https://github.com/mongodb/mongodbatlas-cloudformation-resources/assets/69170650/d6c9b863-0dc6-4a25-ac68-0f604f66f836)
 
to solve this my proposal is keep the same structure that is right now, but add the mappings as a stringify json:

"Fields": [
          "property_name:[{\"type\": \"autocomplete\"},{\"type\": \"string\"}]"
        ]

it has to be a stringify json, due to the fact that cloud formation does not allow dinamic data types like a json object

im creating a version for this change

**Comment by Zuhairahmed** [comment]
just as an update @matsekroth we have a PR open and should be merged in soon: https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/782

**Comment by Zuhairahmed** [comment]
@matsekroth feature was merged as part of https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/801. Give it a try and let us know if you need anything else.
